version: "3.9"

volumes:
  postgres_data:

networks:
    network:

services:
  backend:
    build: .
    container_name: ecommerce-backend-container1
    image: ecommerce-backend1:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:1234@db:5432/e_commerce
      SECRET_KEY: default-secret-key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USERNAME: yashvi.mudgal198@gmail.com
      EMAIL_PASSWORD: qozx kote nhgl jvrq
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network

  db:
    container_name: ecommerce-db-container1
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: e_commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d e_commerce"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network